name: Prod-E-invoicing - Sage Network New Onboarding Process
variables:
- name: productCode
  value: sage100FR
- name: productLicenseType
  value: sage100FR_premium
- name: STSProvider
  value: integrate.my.provider
- name: STSApplication
  value: sage.integrate.myproduct
- name: STSLicenseData
  value: '{\"serial\":\"ACTIVE\"}'
- name: STSVersion
  value: '0'
- name: origin
  value: TgxpqgHddN
- name: nasUrl
  value: https://api-int.network-eng.sage.com
- name: sageNetworkBaseUrl
  value: https://api-int.network-eng.sage.com
- name: connectedBridgeURL
  value: https://api.sandbox.sbc.sage.com/bridge/v4
- name: organisationServiceURL
  value: https://api.sandbox.sbc.sage.com/organisation/v1
- name: sageIdURL
  value: https://id.sage.com
- name: sageIdAuthURL
  value: https://id.auth-shadow.sage.com
- name: client_id
  value: SrPpKzCgY4uS1fAMI79s39XtaXH51LaE
- name: client_secret
  value: Gw82R90wsTW7wzI0m-P40xM7QhKPATjXUWju2wtjl1Bz-1wXoS3vizG8qnoLKwpC
- name: auth_client_id
  value: Tu17UicEi5ND0IUglp0uQcawjErleZCO
- name: provisionAccountEmail
  value: andres.mujica+testapproach@sage.com
- name: context_hint
  value: ''
- name: provisionAccountIdempotency
  value: 5ae795a8-0238-4be0-abc1-24e50b928cd1
- name: provisionAccountBackOfficeId
  value: db4467ac-8f43-4a0b-9835-4e38f8ab91ed
- name: provisionAccountExternalId
  value: 1d0c1609-44fe-4cb9-bb00-eb53f7c80bca
- name: provisionAccountName
  value: Breitenberg - Walker
- name: provisionAccountManagingAccountId
  value: cg7aeb63vlj9eardhgtnphaf0k7e5uywlb83r26iucnjftniky
- name: provisionAccountSubscriptionId
  value: gttg0hbs548sa6eu3k5z2vf0qh4pln54q2mewngrhvomf9bkw7
- name: provisionAccountResponseAccountId
  value: ''
- name: provisionAccountResponseUserId
  value: ''
- name: provisionAccountResponseBusinessId
  value: ''
- name: networkProductInstancesId
  value: ''
- name: networkProductInstancesTenantId
  value: b502961f-8643-3d5a-fa56-bf5998cbe9ae
- name: networkProductInstancesProductCode
  value: ''
- name: contextHintEncoded
  value: PMRFIZLOMFXHISLEEI5CEYTDMU3TCOJTMIWTCYRVG4WTCZLEGQWWIYZTGEWTEOJWMU2GMYRZMM3WEYZCFQRFE33MMVEWI4ZCHJNSEZLSOARF2LBCJ53W4ZLSIVWWC2LMJBUW45BCHIRGC3TEOJSXGLTNOVVGSY3BFN2GK43UMFYHA4TPMFRWQQDTMFTWKLTDN5WSE7I=
- name: contextHintEncodedBuyer
  value: PMRFIZLOMFXHISLEEI5CEYTDMU3TCOJTMIWTCYRVG4WTCZLEGQWWIYZTGEWTEOJWMU2GMYRZMM3WEYZCFQRFE33MMVEWI4ZCHJNSEZLSOARF2LBCJ53W4ZLSIVWWC2LMJBUW45BCHIRGC3TEOJSXGLTNOVVGSY3BFN2GK43UMFYHA4TPMFRWQQDTMFTWKLTDN5WSE7I=
- name: connectorBlobUploadUrl
  value: https://inteuerpsync.blob.core.windows.net/sync/98670864-6d5d-4227-832e-d25c2fe7e466/c8b1a078-57d7-46c9-9a23-9131ae440f06/file.zip?sv=2023-11-03&st=2025-08-20T11%3A28%3A04Z&se=2025-08-21T17%3A28%3A04Z&sr=b&sp=w&sig=wcVTcAyMET%2BU4xX4pEcyCCXcXMQeUx%2BBcqv8y8E4hg8%3D
- name: connectorSyncTaskId
  value: c8b1a078-57d7-46c9-9a23-9131ae440f06
- name: connectorAttachmentId
  value: 5f69a28e-bf7a-4e91-bfac-5a47f50e3a0b
- name: lockstepAPI
  value: https://api.eu.int.lockstep.io
- name: provisionAccountEmailBuyer
  value: demo1@sage.mailinator.com
- name: provisionAccountResponseAccountIdBuyer
  value: ''
- name: provisionAccountResponseUserIdBuyer
  value: ''
- name: provisionAccountResponseBusinessIdBuyer
  value: ''
- name: networkProductInstancesIdBuyer
  value: ''
- name: networkProductInstancesTenantIdBuyer
  value: 3c65465d-c83c-213c-be56-1dce20bd26d3
- name: networkProductInstancesProductCodeBuyer
  value: ''
- name: ADSapi
  value: https://api.eu.int.lockstep.io/api/v1
- name: invoiceIdBuyer
  value: ''
- name: fromNetworkSyncIdBuyer
  value: ''
- name: attachmentdownloadUrl
  value: ''
- name: attachmentId
  value: ''
- name: networkAudience
  value: snet-dev/network/api
- name: audience
  value: snet-dev/network/api
- name: retryCount
  value: ''
- name: buyer_network_token
  value: ''
- name: OrgServiceURL
  value: https://api.sandbox.sbc.sage.com/organisation
- name: LoggedInUserAuth0PrincipalId
  value: auth0|e4f4cabf395f144cd276bdae18f291fedc57f126d73790ff
- name: SubscriptionId
  value: 3f260e49-1532-484c-9a79-c785af8f2bed
- name: provisionAccountIdempotency2
  value: a35b2ebd-96a9-45b2-9119-bd8fde540016
- name: provisionAccountIdempotency3
  value: d131884e-4533-43bd-ad34-a4d3c0d604d1
- name: SubscriptionIdBuyer
  value: 67597fa3-4f79-49de-a2a0-baaca00c56d5
- name: provisionAccountIdempotency5
  value: c38fb670-96c9-4829-ab42-03b5d6742c04
- name: Audience_Sage_Id
  value: SBCDS/Global
- name: Callback_SageID
  value: https://id.sage.com/mobile
- name: sageIdURL_shadow
  value: https://id-shadow.sage.com
